[workspace]
members = [
  "glass-easel-i18n",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true

[patch.crates-io]
glass-easel-template-compiler = { path = "../glass-easel/glass-easel-template-compiler" }
